export const EXACT_LOCATION_ALIASES: Record<string, string> = {
  'quezon city,comonwealth': 'Quezon City, Commonwealth',
  'quezon city, comonwealth': 'Quezon City, Commonwealth',
  'san fernando pampanga': 'San Fernando, Pampanga',
  'sanfernanfo, pampanga': 'San Fernando, Pampanga',
  'sanfernanfo pampanga': 'San Fernando, Pampanga',
  'davao city': 'Davao City',
  'quezon city': 'Quezon City',
  'bacolod city': 'Bacolod City',
  'alcala pangasinan': 'Alcala, Pangasinan',
  'alcala, pangasinan': 'Alcala, Pangasinan',
  'metro manila': 'Manila',
  santotomas: 'Santo Tomas',
  'santotomas pampanga': 'Santo Tomas, Pampanga',
  'porac, pampang': 'Porac, Pampanga',
  'pampanga, anglese city': 'Angeles City, Pampanga',
  'cabantian, davao coty': 'Cabantian, Davao City',
  zambonga: 'Zamboanga',
  cdo: 'Cagayan de Oro City',
  'cagayan de oro': 'Cagayan de Oro City',
  'quezon city metro manila': 'Quezon City, Metro Manila',
  tundo: 'Tondo',
  'culbertson, mt 59218, usa': 'Culbertson, Montana, USA',
  'dubai uae': 'Dubai, United Arab Emirates',
  'dubai, uae': 'Dubai, United Arab Emirates',
  'abu dhabi, uae': 'Abu Dhabi, United Arab Emirates',
  'abu dhabi united arab emirates': 'Abu Dhabi, United Arab Emirates',
  'united arab emirates dubai': 'Dubai, United Arab Emirates',
};
