export const PUBLIC_ENV_KEYS = [
  'NEXT_PUBLIC_FIREBASE_API_KEY',
  'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
  'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
  'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'NEXT_PUBLIC_FIREBASE_APP_ID',
  'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID',
  'NEXT_PUBLIC_FIREBASE_APPCHECK_SITE_KEY',
  'NEXT_PUBLIC_FIREBASE_APPCHECK_DEBUG_TOKEN',
  'NEXT_PUBLIC_TURNSTILE_SITE_KEY',
  'NEXT_PUBLIC_STUDYNAVI_URL',
  'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY',
  'NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID',
  'NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID_DARK',
  'NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID_LIGHT',
] as const;

export type PublicEnvKey = (typeof PUBLIC_ENV_KEYS)[number];
