import type { User } from '../../../../types';
import type { CutoffValue, StaffReport } from './types';
import {
    applyDataCellStyle,
    applyHeaderCellStyle,
    buildDateRange,
    formatMinutes,
    formatSheetDate,
    toDateKey,
    toSafeSheetName,
} from './utils';

type CommonSectionParams = {
    workbook: any;
    staffReports: StaffReport[];
    monthLabel: string;
    selectedCutoff: CutoffValue;
    selectedYear: number;
    generatedAt: string;
};

export const createSummarySheet = ({
    workbook,
    user,
    staffReports,
    branchLabel,
    monthLabel,
    selectedCutoff,
    selectedYear,
    generatedAt,
}: CommonSectionParams & {
    user: User;
    branchLabel: string;
}) => {
    const summarySheet = workbook.addWorksheet('Summary', {
        views: [{ state: 'frozen', ySplit: 9 }],
    });

    summarySheet.columns = [
        { width: 6 },
        { width: 26 },
        { width: 22 },
        { width: 14 },
        { width: 10 },
        { width: 10 },
        { width: 10 },
        { width: 10 },
        { width: 10 },
        { width: 12 },
    ];

    summarySheet.mergeCells('A1:J1');
    const summaryTitle = summarySheet.getCell('A1');
    summaryTitle.value = 'Timesheet Download Report';
    summaryTitle.font = { name: 'Calibri', size: 22, bold: true, color: { argb: 'FF1D4ED8' } };
    summaryTitle.alignment = { vertical: 'middle', horizontal: 'left' };
    summaryTitle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4F8FF' } };
    summarySheet.getRow(1).height = 34;

    const summaryMeta: Array<[string, string]> = [
        ['Generated By', user.displayName || user.email || 'System'],
        ['Generated At', generatedAt],
        ['Branch', branchLabel],
        ['Coverage', `${monthLabel} ${selectedCutoff}, ${selectedYear}`],
    ];
    summaryMeta.forEach(([label, value], index) => {
        const row = summarySheet.getRow(2 + index);
        row.getCell(1).value = label;
        row.getCell(1).font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF111827' } };
        row.getCell(2).value = value;
        row.getCell(2).font = { name: 'Calibri', size: 11, color: { argb: 'FF111827' } };
    });

    summarySheet.mergeCells('A7:J7');
    const summarySectionTitle = summarySheet.getCell('A7');
    summarySectionTitle.value = 'Staff Summary';
    summarySectionTitle.font = { name: 'Calibri', size: 16, bold: true, color: { argb: 'FF111827' } };
    summarySectionTitle.alignment = { vertical: 'middle', horizontal: 'left' };
    summarySectionTitle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
    summarySheet.getRow(7).height = 26;

    const summaryHeader = summarySheet.getRow(9);
    summaryHeader.values = ['#', 'Name', 'Role', 'Branch', 'Present', 'On Leave', 'Offset', 'Pending', 'Absent', 'Total Hours'];
    summaryHeader.height = 22;
    summaryHeader.eachCell((cell: any) => applyHeaderCellStyle(cell));

    staffReports.forEach((staff, index) => {
        const row = summarySheet.addRow([
            index + 1,
            staff.name,
            staff.role,
            staff.branch,
            staff.presentDays,
            staff.leaveDays,
            staff.offsetDays,
            staff.pendingDays,
            staff.absentDays,
            formatMinutes(staff.totalMinutes),
        ]);

        row.height = 20;
        row.eachCell((cell: any, colNumber: number) => {
            const isCenter = colNumber === 1 || (colNumber >= 5 && colNumber <= 10);
            applyDataCellStyle(cell, isCenter ? 'center' : 'left');
        });

        if (row.number % 2 === 0) {
            row.eachCell((cell: any) => {
                cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFAFCFF' } };
            });
        }
    });
};

export const createStaffSheets = ({
    workbook,
    staffReports,
    monthLabel,
    selectedCutoff,
    selectedYear,
    periodStart,
    periodEnd,
    generatedAt,
}: CommonSectionParams & {
    periodStart: Date;
    periodEnd: Date;
}) => {
    const periodDates = buildDateRange(periodStart, periodEnd);
    const usedSheetNames = new Set<string>(['Summary']);

    staffReports.forEach((staff, index) => {
        const logsByDate = new Map<string, any>();
        staff.logs.forEach((log) => {
            logsByDate.set(toDateKey(log.date), log);
        });

        const rows: (string | number)[][] = [
            ['Staff Name', staff.name],
            ['Role', staff.role],
            ['Branch', staff.branch],
            ['Coverage', `${monthLabel} ${selectedCutoff}, ${selectedYear}`],
            [],
            ['Date', 'Day', 'Status', 'AM Time In', 'AM Time Out', 'PM Time In', 'PM Time Out', 'Total Hours', 'Remarks'],
        ];

        periodDates.forEach((date) => {
            const key = toDateKey(date);
            const log = logsByDate.get(key);
            rows.push([
                formatSheetDate(date),
                date.toLocaleDateString('en-US', { weekday: 'long' }),
                log?.status || 'No Record',
                log?.timeIn?.time || '--:--',
                log?.lunchStart?.time || '--:--',
                log?.lunchEnd?.time || '--:--',
                log?.timeOut?.time || '--:--',
                log?.totalHours || '--',
                log?.remarks || log?.notes || '',
            ]);
        });

        const rawSheetName = `${index + 1}. ${staff.name}`;
        const sheetName = toSafeSheetName(rawSheetName, usedSheetNames);
        const staffSheet = workbook.addWorksheet(sheetName, {
            views: [{ state: 'frozen', ySplit: 7 }],
        });

        staffSheet.columns = [
            { width: 14 },
            { width: 12 },
            { width: 16 },
            { width: 10 },
            { width: 12 },
            { width: 10 },
            { width: 10 },
            { width: 12 },
            { width: 34 },
        ];

        staffSheet.mergeCells('A1:I1');
        const staffTitle = staffSheet.getCell('A1');
        staffTitle.value = `${staff.name} - Timesheet`;
        staffTitle.font = { name: 'Calibri', size: 18, bold: true, color: { argb: 'FF1D4ED8' } };
        staffTitle.alignment = { vertical: 'middle', horizontal: 'left' };
        staffTitle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4F8FF' } };
        staffSheet.getRow(1).height = 30;

        const staffMeta: Array<[string, string]> = [
            ['Role', staff.role],
            ['Branch', staff.branch],
            ['Coverage', `${monthLabel} ${selectedCutoff}, ${selectedYear}`],
            ['Generated At', generatedAt],
        ];
        staffMeta.forEach(([label, value], metaIndex) => {
            const row = staffSheet.getRow(2 + metaIndex);
            row.getCell(1).value = label;
            row.getCell(1).font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF111827' } };
            row.getCell(2).value = value;
            row.getCell(2).font = { name: 'Calibri', size: 11, color: { argb: 'FF111827' } };
        });

        const staffHeader = staffSheet.getRow(7);
        staffHeader.values = rows[5];
        staffHeader.height = 22;
        staffHeader.eachCell((cell: any) => applyHeaderCellStyle(cell));

        rows.slice(6).forEach((record, rowIndex) => {
            const row = staffSheet.addRow(record);
            row.height = 20;
            row.eachCell((cell: any, colNumber: number) => {
                const isCenter = colNumber >= 2 && colNumber <= 8;
                applyDataCellStyle(cell, isCenter ? 'center' : 'left');
            });
            if (rowIndex % 2 === 1) {
                row.eachCell((cell: any) => {
                    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFAFCFF' } };
                });
            }
        });
    });
};
