import type { AppShellActions, AppShellState } from '../AppShell.types';
import type { AppShellContainerProps } from './AppShellContainer.types';
import { IMAGE_LINKS } from '@/config/imageLinks';

export const buildAppShellState = ({
    user,
    userRole,
    view,
    theme,
    isReady,
    ui,
    navItems,
    confirmModal,
    notificationsState,
    data,
    timeTracking,
}: AppShellContainerProps): AppShellState => {
    const logoUrl = theme === 'dark' ? IMAGE_LINKS.branding.logoDark : IMAGE_LINKS.branding.logoLight;

    return {
        user,
        userRole,
        view,
        theme,
        isSidebarCollapsed: ui.isSidebarCollapsed,
        isMobileSidebarOpen: ui.isMobileSidebarOpen,
        isNotificationDropdownOpen: ui.isNotificationDropdownOpen,
        persistentNotifications: notificationsState.persistentNotifications,
        notifications: notificationsState.notifications,
        notificationCount: notificationsState.unreadCount,
        navItems,
        leads: data.leads,
        assessmentSubmissions: data.assessmentSubmissions,
        genuineSubmissionIds: data.genuineSubmissionIds,
        applications: data.applications,
        allPersonnel: data.allPersonnel,
        openApplication: data.openApplication,
        openLeadForApplication: data.openLeadForApplication,
        openStudentLead: data.openStudentLead,
        openStudentModalId: data.openStudentModalId,
        applicationsForOpenStudent: data.applicationsForOpenStudent,
        minimizedLeads: data.minimizedLeads,
        modalInitialTab: data.modalInitialTab,
        timeTrackingStatus: timeTracking.timeTrackingStatus,
        timeLog: timeTracking.timeLog,
        hasTimedInToday: timeTracking.hasTimedInToday,
        hasTakenLunchToday: timeTracking.hasTakenLunchToday,
        isTransferModalOpen: ui.isTransferModalOpen,
        leadToTransfer: ui.leadToTransfer,
        isRequestLeaveModalOpen: ui.isRequestLeaveModalOpen,
        isRequestOffsetModalOpen: ui.isRequestOffsetModalOpen,
        isRequestUseOffsetModalOpen: ui.isRequestUseOffsetModalOpen,
        confirmModal,
        isReady,
        logoUrl,
    };
};

export const buildAppShellActions = ({
    toggleTheme,
    ui,
    notificationsState,
    handlers,
    timeTracking,
}: AppShellContainerProps): AppShellActions => ({
    toggleTheme,
    onToggleSidebarCollapse: ui.toggleSidebarCollapsed,
    onOpenMobileSidebar: ui.openMobileSidebar,
    onCloseMobileSidebar: ui.closeMobileSidebar,
    onLogout: handlers.handleLogout,
    onClearNotifications: notificationsState.clearPersistentNotifications,
    onNotificationDropdownToggle: ui.setNotificationDropdownOpen,
    onOpenStudentProfile: ui.openStudentProfile,
    onOpenApplicationDetail: ui.openApplicationDetail,
    onOpenProfile: () => ui.setView('profile'),
    onNavigateToDashboard: () => ui.setView('dashboard'),
    onNavigateToLeads: () => ui.setView('leads'),
    onNavigateToApplications: () => ui.setView('applications'),
    onNavigateToArchive: () => ui.setView('archive'),
    onNavigateToEducationProviders: () => ui.setView('education-providers'),
    onNavigateToTimesheet: () => ui.setView('timesheet'),
    onNavigateToPersonnel: () => ui.setView('personnel'),
    onNavigateToNotifications: ui.openNotifications,
    onRequestTransfer: ui.openTransferModal,
    onUpdateLead: handlers.updateLead,
    onAddLogEntry: handlers.addLogEntry,
    onAddNote: handlers.addNote,
    onUpdateApplication: handlers.updateApplication,
    onStatusUpdateWithNote: handlers.handleStatusUpdateWithNote,
    showPopup: handlers.showPopup,
    onProfileUpdate: handlers.handleProfileUpdate,
    onLoginAgain: handlers.onLoginAgain,
    onOpenRequestLeaveModal: ui.openRequestLeaveModal,
    onOpenRequestOffsetModal: ui.openRequestOffsetModal,
    onOpenRequestUseOffsetModal: ui.openRequestUseOffsetModal,
    onBranchChangeRequestSubmit: handlers.onBranchChangeRequestSubmit,
    onCloseNotification: notificationsState.removeNotification,
    onCloseConfirm: handlers.closeConfirm,
    onCloseStudentModal: ui.closeStudentModal,
    onMinimizeStudentModal: ui.minimizeStudentModal,
    onRestoreMinimized: ui.restoreMinimized,
    onCloseMinimized: ui.closeMinimized,
    onSubmitTransfer: handlers.handleSubmitTransfer,
    onCloseTransferModal: ui.closeTransferModal,
    onCloseRequestLeaveModal: ui.closeRequestLeaveModal,
    onSubmitRequestLeave: handlers.handleRequestLeaveSubmit,
    onCloseRequestOffsetModal: ui.closeRequestOffsetModal,
    onSubmitRequestOffset: handlers.handleRequestOffsetSubmit,
    onCloseRequestUseOffsetModal: ui.closeRequestUseOffsetModal,
    onTimeIn: timeTracking.promptTimeIn,
    onTimeOut: timeTracking.promptTimeOut,
    onStartLunch: timeTracking.handleStartLunch,
    onEndLunch: timeTracking.handleEndLunch,
});
