export const approvedManualOverridePairs: Array<[string, string]> = [
  ['pathfinder page ads', 'Facebook Page'],
  ['cebu pathfinder page ads', 'Facebook Page'],
  ['cebu pathfinder page chat armand', 'Facebook Page'],
  ['chat with pathfinder armand', 'Facebook Page'],
  ['christine jean lacang', 'Facebook Page'],
  ['facebook', 'Facebook Page'],
  ['.facebook', 'Facebook Page'],
  ['pathfinder cebu ads', 'Facebook Page'],
  ['pathfinder page chat', 'Facebook Page'],
  ['pathfinder page chat armand', 'Facebook Page'],
  ['angeles city science high school', 'University/School Website'],
  ['college expo in my school', 'University/School Website'],
  ['direct inquiry via email', 'Billboards, Flyers, Brochures, Advertisment'],
  ['direct phone call', 'Billboards, Flyers, Brochures, Advertisment'],
  ['direct phone call to cebu branch', 'Billboards, Flyers, Brochures, Advertisment'],
  ['just saw the branch', 'Billboards, Flyers, Brochures, Advertisment'],
  ['office visit', 'Billboards, Flyers, Brochures, Advertisment'],
  ['walk in', 'Billboards, Flyers, Brochures, Advertisment'],
  ['walk-in', 'Billboards, Flyers, Brochures, Advertisment'],
  ['friend', 'Referred by Family, Relatives, Partners or Friend'],
  ['from cousin', 'Referred by Family, Relatives, Partners or Friend'],
  ['i used this agent before for my undergrad', 'Referred by Family, Relatives, Partners or Friend'],
  ['i was made aware by a senior', 'Referred by Family, Relatives, Partners or Friend'],
  ['my brother applied his student visa also here.', 'Referred by Family, Relatives, Partners or Friend'],
  ['referral', 'Referred by Family, Relatives, Partners or Friend'],
  ['referred by a friend', 'Referred by Family, Relatives, Partners or Friend'],
  ['referred by my sister in belgium', 'Referred by Family, Relatives, Partners or Friend'],
  ['sister', 'Referred by Family, Relatives, Partners or Friend'],
  ['i was referred by a pathfinder staff', 'Staff Referral'],
  ['armand- direct call ( personal lead )', 'Staff Referral'],
  ['friends referral - nerissa student', 'Staff Referral'],
  ['mavi - personal lead', 'Staff Referral'],
  ['mavi parra', 'Staff Referral'],
  ['ms en student', 'Staff Referral'],
  ['personal leads- mandy', 'Staff Referral'],
  ['referral- nerissa', 'Staff Referral'],
  ['referred by education counsellor bea ( personal leads )', 'Staff Referral'],
  ["i watched yvonne's ticktock video", 'TikTok Influencers'],
  ['yvonne', 'TikTok Influencers'],
  ['website / email', 'Website'],
];
